changelog:
  exclude:
    labels:
      - ignore-for-release
      - dependencies
      - chore
  categories:
    - title: Features
      labels:
        - feature
        - enhancement
    - title: Fixes
      labels:
        - fix
        - bug
        - bugfix
    - title: Documentation
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"
