module.exports = {
  safelist: [
    'group-[.desktop1]:flex',
    'group-[.desktop2]:flex',
    'group-[.desktop3]:flex',
    'group-[.desktop4]:flex',
    'group-[.desktop5]:flex',
    'group-[.desktop6]:flex',
    'group-[.desktop7]:flex',
    'group-[.desktop8]:flex',
    'group-[.desktop9]:flex',
    'ml-[0rem]',
    'ml-[1rem]',
    'ml-[2rem]',
    'ml-[3rem]',
    'ml-[4rem]',
    'ml-[5rem]',
    'ml-[6rem]',
    'ml-[7rem]',
    'ml-[8rem]',
    'ml-[9rem]',
  ],
};
