module.exports = {
  safelist: [
    'group-[.desktop-1]:flex',
    'group-[.desktop-2]:flex',
    'group-[.desktop-3]:flex',
    'group-[.desktop-4]:flex',
    'group-[.desktop-5]:flex',
    'group-[.desktop-6]:flex',
    'group-[.desktop-7]:flex',
    'group-[.desktop-8]:flex',
    'group-[.desktop-9]:flex',
    'ml-[0rem]',
    'ml-[1rem]',
    'ml-[2rem]',
    'ml-[3rem]',
    'ml-[4rem]',
    'ml-[5rem]',
    'ml-[6rem]',
    'ml-[7rem]',
    'ml-[8rem]',
    'ml-[9rem]',
  ],
};
