import { type IShortcutMap, EShortcutGroup } from '~/types';

export const SHORTCUTS_MAP: IShortcutMap = {
  id: 'generic-iso',
  name: 'Generic ISO',
  shortcuts: {
    preferences: { key: 'CmdOrCtrl+,', label: 'Preferences', group: EShortcutGroup.General },
    performCommand: { key: 'CmdOrCtrl+P', label: 'Perform command', group: EShortcutGroup.General },
    toggleSidebar: { key: 'CmdOrCtrl+S', label: 'Toggle sidebar', group: EShortcutGroup.General },
    toggleMaximizeArea: {
      key: 'CmdOrCtrl+I',
      label: 'Toggle maximize area',
      group: EShortcutGroup.General,
    },
    goBack: { key: 'CmdOrCtrl+Left', label: 'Go back', group: EShortcutGroup.Navigation },
    goForward: { key: 'CmdOrCtrl+Right', label: 'Go forward', group: EShortcutGroup.Navigation },
    copyUrl: { key: 'CmdOrCtrl+Shift+C', label: 'Copy URL', group: EShortcutGroup.Navigation },
    editUrl: { key: 'CmdOrCtrl+E', label: 'Edit URL', group: EShortcutGroup.Navigation },
    findInPage: { key: 'CmdOrCtrl+F', label: 'Find in page', group: EShortcutGroup.Navigation },
    newTab: { key: 'CmdOrCtrl+T', label: 'New tab', group: EShortcutGroup.TabManagement },
    newWindow: { key: 'CmdOrCtrl+N', label: 'New window', group: EShortcutGroup.WindowManagement },
    pasteAndGo: {
      key: '',
      label: 'Paste and go',
      group: EShortcutGroup.TabManagement,
    },
    openRecentlyClosed: {
      key: 'Shift+CmdOrCtrl+T',
      label: 'Open recently closed tab',
      group: EShortcutGroup.TabManagement,
    },
    closeTab: { key: 'CmdOrCtrl+W', label: 'Close tab', group: EShortcutGroup.TabManagement },
    reloadTab: { key: 'CmdOrCtrl+R', label: 'Reload', group: EShortcutGroup.TabManagement },
    suspendTab: {
      key: 'CmdOrCtrl+Shift+S',
      label: 'Suspend tab',
      group: EShortcutGroup.TabManagement,
    },
    moveTabUp: {
      key: 'CmdOrCtrl+Alt+]',
      label: 'Move tab up',
      group: EShortcutGroup.TabManagement,
    },
    moveTabDown: {
      key: 'CmdOrCtrl+Alt+[',
      label: 'Move tab down',
      group: EShortcutGroup.TabManagement,
    },
    selectTab1: { key: 'CmdOrCtrl+1', label: 'Tab 1', group: EShortcutGroup.TabNavigation },
    selectTab2: { key: 'CmdOrCtrl+2', label: 'Tab 2', group: EShortcutGroup.TabNavigation },
    selectTab3: { key: 'CmdOrCtrl+3', label: 'Tab 3', group: EShortcutGroup.TabNavigation },
    selectTab4: { key: 'CmdOrCtrl+4', label: 'Tab 4', group: EShortcutGroup.TabNavigation },
    selectTab5: { key: 'CmdOrCtrl+5', label: 'Tab 5', group: EShortcutGroup.TabNavigation },
    selectTab6: { key: 'CmdOrCtrl+6', label: 'Tab 6', group: EShortcutGroup.TabNavigation },
    selectTab7: { key: 'CmdOrCtrl+7', label: 'Tab 7', group: EShortcutGroup.TabNavigation },
    selectTab8: { key: 'CmdOrCtrl+8', label: 'Tab 8', group: EShortcutGroup.TabNavigation },
    selectTab9: { key: 'CmdOrCtrl+9', label: 'Tab 9', group: EShortcutGroup.TabNavigation },
    previousTab: { key: 'CmdOrCtrl+]', label: 'Previous tab', group: EShortcutGroup.TabNavigation },
    nextTab: { key: 'CmdOrCtrl+[', label: 'Next tab', group: EShortcutGroup.TabNavigation },
    findTab: { key: 'CmdOrCtrl+.', label: 'Find tab', group: EShortcutGroup.TabNavigation },
    tabSwitcher: { key: 'Control+Tab', label: 'Tab switcher', group: EShortcutGroup.TabNavigation },
    tabMarks: { key: 'CmdOrCtrl+;', label: 'Marks', group: EShortcutGroup.TabNavigation },
    selectTabAttention: {
      key: 'CmdOrCtrl+U',
      label: 'Select tab requiring attention',
      group: EShortcutGroup.TabNavigation,
    },
    zoomIn: { key: 'CmdOrCtrl+Plus', label: 'Zoom in', group: EShortcutGroup.Zoom },
    zoomOut: { key: 'CmdOrCtrl+-', label: 'Zoom out', group: EShortcutGroup.Zoom },
    zoomReset: { key: 'CmdOrCtrl+0', label: 'Zoom reset', group: EShortcutGroup.Zoom },
    findDesktop: { key: 'CmdOrCtrl+D', label: 'Find desktop', group: EShortcutGroup.Desktops },
    selectDesktop1: {
      key: 'Shift+CmdOrCtrl+1',
      label: 'Desktop 1',
      group: EShortcutGroup.Desktops,
    },
    selectDesktop2: {
      key: 'Shift+CmdOrCtrl+2',
      label: 'Desktop 2',
      group: EShortcutGroup.Desktops,
    },
    selectDesktop3: {
      key: 'Shift+CmdOrCtrl+3',
      label: 'Desktop 3',
      group: EShortcutGroup.Desktops,
    },
    selectDesktop4: {
      key: 'Shift+CmdOrCtrl+4',
      label: 'Desktop 4',
      group: EShortcutGroup.Desktops,
    },
    selectDesktop5: {
      key: 'Shift+CmdOrCtrl+5',
      label: 'Desktop 5',
      group: EShortcutGroup.Desktops,
    },
    selectDesktop6: {
      key: 'Shift+CmdOrCtrl+6',
      label: 'Desktop 6',
      group: EShortcutGroup.Desktops,
    },
    selectDesktop7: {
      key: 'Shift+CmdOrCtrl+7',
      label: 'Desktop 7',
      group: EShortcutGroup.Desktops,
    },
    selectDesktop8: {
      key: 'Shift+CmdOrCtrl+8',
      label: 'Desktop 8',
      group: EShortcutGroup.Desktops,
    },
    selectDesktop9: {
      key: 'Shift+CmdOrCtrl+9',
      label: 'Desktop 9',
      group: EShortcutGroup.Desktops,
    },
    previousDesktop: {
      key: 'Shift+CmdOrCtrl+[',
      label: 'Previous desktop',
      group: EShortcutGroup.Desktops,
    },
    nextDesktop: {
      key: 'Shift+CmdOrCtrl+]',
      label: 'Next desktop',
      group: EShortcutGroup.Desktops,
    },
    openBookmark: { key: 'CmdOrCtrl+B', label: 'Open bookmark', group: EShortcutGroup.Bookmarks },
  },
};
