import type { IShortcutMap } from '../types';

export const SHORTCUTS_MAP: IShortcutMap = {
  id: 'macos-iso',
  name: 'Mac OS ISO',
  shortcuts: {
    preferences: { key: 'CmdOrCtrl+,', label: 'Preferences' },
    performCommand: { key: 'CmdOrCtrl+P', label: 'Perform command' },
    newTab: { key: 'CmdOrCtrl+T', label: 'New tab' },
    openRecentlyClosed: { key: 'Shift+CmdOrCtrl+T', label: 'Open recently closed tab' },
    copyUrl: { key: 'CmdOrCtrl+Shift+C', label: 'Copy URL' },
    editUrl: { key: 'CmdOrCtrl+E', label: 'Edit URL' },
    findInPage: { key: 'CmdOrCtrl+F', label: 'Find in page' },
    toggleSidebar: { key: 'CmdOrCtrl+S', label: 'Toggle sidebar' },
    toggleMaximizeArea: { key: 'CmdOrCtrl+I', label: 'Toggle maximize area' },
    findDesktop: { key: 'CmdOrCtrl+D', label: 'Find desktop' },
    selectDesktop1: { key: 'Shift+CmdOrCtrl+1', label: 'Desktop 1' },
    selectDesktop2: { key: 'Shift+CmdOrCtrl+2', label: 'Desktop 2' },
    selectDesktop3: { key: 'Shift+CmdOrCtrl+3', label: 'Desktop 3' },
    selectDesktop4: { key: 'Shift+CmdOrCtrl+4', label: 'Desktop 4' },
    selectDesktop5: { key: 'Shift+CmdOrCtrl+5', label: 'Desktop 5' },
    selectDesktop6: { key: 'Shift+CmdOrCtrl+6', label: 'Desktop 6' },
    selectDesktop7: { key: 'Shift+CmdOrCtrl+7', label: 'Desktop 7' },
    selectDesktop8: { key: 'Shift+CmdOrCtrl+8', label: 'Desktop 8' },
    selectDesktop9: { key: 'Shift+CmdOrCtrl+9', label: 'Desktop 9' },
    previousDesktop: { key: 'Shift+CmdOrCtrl+[', label: 'Previous desktop' },
    nextDesktop: { key: 'Shift+CmdOrCtrl+]', label: 'Next desktop' },
    findTab: { key: 'CmdOrCtrl+.', label: 'Find tab' },
    selectTab1: { key: 'CmdOrCtrl+1', label: 'Tab 1' },
    selectTab2: { key: 'CmdOrCtrl+2', label: 'Tab 2' },
    selectTab3: { key: 'CmdOrCtrl+3', label: 'Tab 3' },
    selectTab4: { key: 'CmdOrCtrl+4', label: 'Tab 4' },
    selectTab5: { key: 'CmdOrCtrl+5', label: 'Tab 5' },
    selectTab6: { key: 'CmdOrCtrl+6', label: 'Tab 6' },
    selectTab7: { key: 'CmdOrCtrl+7', label: 'Tab 7' },
    selectTab8: { key: 'CmdOrCtrl+8', label: 'Tab 8' },
    selectTab9: { key: 'CmdOrCtrl+9', label: 'Tab 9' },
    previousTab: { key: 'CmdOrCtrl+]', label: 'Previous tab' },
    nextTab: { key: 'CmdOrCtrl+[', label: 'Next tab' },
    selectTabAttention: { key: 'CmdOrCtrl+U', label: 'Select tab requiring attention' },
    tabSwitcher: { key: 'Control+Tab', label: 'Tab switcher' },
    tabMarks: { key: 'CmdOrCtrl+;', label: 'Marks' },
    moveTabUp: { key: 'CmdOrCtrl+Alt+]', label: 'Move tab up' },
    moveTabDown: { key: 'CmdOrCtrl+Alt+[', label: 'Move tab down' },
    suspendTab: { key: 'CmdOrCtrl+Shift+S', label: 'Suspend tab' },
    closeTab: { key: 'CmdOrCtrl+W', label: 'Close tab' },
    reloadTab: { key: 'CmdOrCtrl+R', label: 'Reload' },
    goBack: { key: 'CmdOrCtrl+Left', label: 'Go back' },
    goForward: { key: 'CmdOrCtrl+Right', label: 'Go forward' },
    zoomIn: { key: 'CmdOrCtrl+Plus', label: 'Zoom in' },
    zoomOut: { key: 'CmdOrCtrl+-', label: 'Zoom out' },
    zoomReset: { key: 'CmdOrCtrl+0', label: 'Zoom reset' },
    openBookmark: { key: 'CmdOrCtrl+B', label: 'Open bookmark' },
  },
};
