import path from 'path';

export enum EIcon {
  Back = 'back.png',
  Bookmarks = 'bookmarks.png',
  Close = 'close.png',
  Command = 'command.png',
  Copy = 'copy.png',
  Desktop = 'desktop.png',
  Divider = 'divider.png',
  Down = 'down.png',
  Edit = 'edit.png',
  File = 'file.png',
  Folder = 'folder.png',
  Forward = 'forward.png',
  Horizontal = 'horizontal.png',
  Info = 'info.png',
  Logo = 'logo.png',
  Maximize = 'maximize.png',
  Move = 'move.png',
  Mute = 'mute.png',
  Next = 'next.png',
  Notification = 'notification.png',
  Open = 'open.png',
  Partition = 'partition.png',
  Previous = 'previous.png',
  PreviousVisited = 'previous-visited.png',
  Reload = 'reload.png',
  RotateLeft = 'rotate-left.png',
  RotateRight = 'rotate-right.png',
  Search = 'search.png',
  Sidebar = 'sidebar.png',
  Size = 'size.png',
  Suspend = 'suspend.png',
  Tab = 'tab.png',
  Theme = 'theme.png',
  Unmute = 'unmute.png',
  Unsplit = 'unsplit.png',
  Up = 'up.png',
  Vertical = 'vertical.png',
  Windows = 'windows.png',
}

export function getIcon(name: EIcon): string {
  return path.join(__dirname, 'assets', 'icons', name);
}
